- spec/requests/orders_spec.rb
- spec/requests/registrations_spec.rb
- spec/requests/stocks_spec.rb
> requests_tests_v2

- spec/system/creating_users_spec.rb
- spec/system/deleting_users_spec.rb
- spec/system/showing_users_spec.rb
- spec/system/signing_in_users_spec.rb
- spec/system/signing_up_users_spec.rb
- spec/system/updating_users_spec.rb
> users_system_tests_v2

- spec/system/creating_stocks_spec.rb
- spec/system/deleting_stocks_spec.rb
- spec/system/showing_stocks_spec.rb
- spec/system/updating_stocks_spec.rb
> stocks_system_tests

- spec/system/creating_orders_spec.rb
- spec/system/selling_orders_spec.rb
- spec/system/showing_orders_spec.rb
> orders_system_tests_v2

- spec/mailers/user_mailer_spec.rb
> mailer_test

- spec/models/user_spec.rb
> model_tests_v2

- spec/models/user_spec.rb
> user_model_tests_v2

- config/environments/production.rb
> Changed default URL in production

- config/environments/production.rb
> Removed port number

- app/controllers/application_controller.rb
- app/controllers/orders_controller.rb
- app/helpers/orders_helper.rb
- app/models/order.rb
- db/migrate/20210901085624_add_money_to_users.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/order.rb
- spec/factories/stock.rb
- spec/factories/user.rb
- spec/models/order_spec.rb
> money_attribute

- app/controllers/orders_controller.rb
- app/controllers/stocks_controller.rb
- app/helpers/application_helper.rb
- app/helpers/orders_helper.rb
- app/helpers/stocks_helper.rb
- app/models/order.rb
- app/views/orders/_form.html.haml
- app/views/orders/all.html.haml
- app/views/orders/new.html.haml
- app/views/stocks/market.html.haml
- app/views/stocks/top_up.html.haml
- config/routes.rb
- db/seeds.rb
- spec/models/order_spec.rb
- spec/requests/orders_spec.rb
> Added features

- Gemfile
- Gemfile.lock
> iex_ruby_client_gem

- app/models/order.rb
- app/models/user.rb
- app/views/orders/new.html.haml
- spec/factories/order.rb
- spec/factories/stock.rb
- spec/models/order_spec.rb
- spec/requests/orders_spec.rb
> order_model_and_test

- app/views/stocks/market.html.haml
- spec/factories/user.rb
- spec/requests/homes_spec.rb
- spec/requests/stocks_spec.rb
> Requests_test_v3

- app/models/stock.rb
- config/initializers/iex.rb
> IEX Configs

- spec/system/creating_orders_spec.rb
- spec/system/selling_orders_spec.rb
- spec/system/topping_up_moneys_spec.rb
> System_tests_v3

- .gitignore
- Gemfile
- Gemfile.lock
> Dotenv_vars

- app/helpers/orders_helper.rb
> Updated buy and sell method

- app/models/stock.rb
- config/routes.rb
> Added search methods

- app/controllers/stocks_controller.rb
- app/models/stock.rb
- app/views/orders/_form.html.haml
- app/views/stocks/_form.html.haml
- app/views/stocks/_search_form.html.haml
- app/views/stocks/index.html.haml
- app/views/stocks/new.html.haml
- spec/system/creating_stocks_spec.rb
> Stock Search UI

- app/views/stocks/market.html.haml
- app/views/stocks/top_up.html.haml
> Replaced currency from peso to dollars in the display

- spec/requests/stocks_spec.rb
- spec/system/creating_orders_spec.rb
- spec/system/creating_stocks_spec.rb
- spec/system/selling_orders_spec.rb
> Improved_rspec_tests

- .rubocop.yml
- app/controllers/stocks_controller.rb
- app/helpers/stocks_helper.rb
- app/models/stock.rb
- app/views/stocks/_form.html.haml
- app/views/stocks/_search_form.html.haml
- app/views/stocks/index.html.haml
- app/views/stocks/market.html.haml
- spec/factories/stock.rb
- spec/requests/stocks_spec.rb
- spec/system/creating_stocks_spec.rb
> Loophole_fix_improvement_v2

- app/controllers/orders_controller.rb
- app/controllers/stocks_controller.rb
- spec/system/creating_stocks_spec.rb
> Creating_orders_and_stocks_fix

- .rubocop.yml
- app/controllers/stocks_controller.rb
- app/helpers/stocks_helper.rb
> Apply session

- app/helpers/application_helper.rb
- app/views/devise/shared/_links.html.haml
> Refactor login and signup views
